language: java

jdk:
  - oraclejdk8

addons:
  chrome: stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Skip Install Step
install: true

script: "mvn -B clean test jacoco:report coveralls:report -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

notifications:
  email:
    recipients:
      - deVinnnie@users.noreply.github.com

    on_success: change
    on_failure: always