language: java

jdk:
  - openjdk11

# Skip Install Step
install: true

script: "./gradlew --stacktrace clean build integrationTest jacocoTestReport" # //coveralls

deploy:
  provider: heroku
  skip_cleanup: true
  api-key:
    secure: $HEROKU_API_KEY
  app: mirajeugdkern-mailinglist