version: '2'

services:
  db:
    image: postgres:10.18
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      #POSTGRES_USER: postgres
      #POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/postgres
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: postgres
      consult_password: pw
      consult_user: user
      spring.mail.from: me
      spring.mail.password: bla
      spring.mail.username: bla
    ports:
      - "8080:8080"
